### ISSUE TITLE
用idea导入运行的时候报错

### ISSUE THREAD

**Issue by leexiangg** [allanzhuo/yyblog#10]
启动的时候报这个错：
Unable to start EmbeddedWebApplicationContext due to missing EmbeddedServletContainerFactory bean.

找了很多方式都没解决，不知道up主有没有收到这个错误的反馈。
我的微信：13391639121，希望能收到您的回复

**Comment by allanzhuo** [comment]
1、请先确认依赖包是否全部下载完成
2、本地导入后，直接运行Appstart.java文件
请确认后在尝试下，我这边本地跑还没出现过这个问题

**Comment by leexiangg** [comment]
非常感谢您的答疑。重新配置qq-connect后，已经运行起来了。
