### ISSUE TITLE
请问下这个包是从哪里导入的，是你说的qq互联的那个包么?

### ISSUE THREAD

**Issue by gliiii** [allanzhuo/yyblog#16]
![image](https://user-images.githubusercontent.com/47062805/115138899-821ad300-a061-11eb-9d15-1dfe5c9eb2c6.png)

**Comment by allanzhuo** [comment]
是的，把文档里的jar包安装在你本地就可以了

**Comment by gliiii** [comment]
> 是的，把文档里的jar包安装在你本地就可以了

谢谢
