### ISSUE TITLE
unable to login

### ISSUE THREAD

**Issue by bq1028** [allanzhuo/yyblog#3]
The problems met under Linux env:    
 
1.  the table name need to be upper case except for  sys_log and sys_task

2.  error occurred when login ,  the err msg as below:
     Authentication failed for token submission [org.apache.shiro.authc.UsernamePasswordToken - admin, rememberMe=false]. Possible unexpected error? (Typical or expected login exceptions should extend from AuthenticationException).
 
  Check on server,  found the login event record in sys_log. 

  the md5 pwd send to server mismatch with md5 pwd of database.

**Comment by bq1028** [comment]
The improving point to suggest to :  
the table name can be auto-deployment  like hibernate,   refer to  [springboot+mybatis auto create table
](https://github.com/zyf970617/mybatis-auto-create-table)

**Comment by allanzhuo** [comment]
1、数据库大写的问题，应该是你本地数据库的问题配置的问题。可以修改mysql配置不区分大小写，或者将脚本表名修改为大写。
2、密码不匹配的问题，请根据/lib/yyblog.sql，重新创建sys_user表，默认的管理员账号也可根据sql文件初始化。10.25 sys_user新增了wx_open_id，新增blog_collect表。请注意采用的是最新的sql。请检查初始化后密码为：14e1b600b1fd579f47433b88e8d85291  MD5二次加密：123456
3、自动创建表的问题，后续在springboot2.0升级重构的时候考虑。预计年后开始重写前后端时加入。
请方便尝试下上述方法可否解决。

**Comment by bq1028** [comment]
thank you so much for your kind reply and help,  the job you done is great !
