### ISSUE TITLE
GC问题

### ISSUE THREAD

**Issue by trotyzyq** [allanzhuo/yyblog#7]
你好，在我并没有进行操作的情况下，我发现GC的间隔时间很短，是定时任务的问题吗~
参数: -Xms400m -Xmx400m -XX:NewRatio=1
![image](https://user-images.githubusercontent.com/26846709/51965679-43f76000-24a5-11e9-8016-a0a36b2a50c4.png)

**Comment by allanzhuo** [comment]
我记得默认情况下是没有定时任务启动的。如果你没添加任务，即使启动也不会出现这种情况，默认的定时任务没有创建对象呀。另外，方便问下你这是用什么工具查看的吗。

**Comment by trotyzyq** [comment]
我这边设置的新生代刚好是200M,根据显示也确实是200M左右发生了垃圾回收。而且我这是刚启动的项目，老年代的对象基本也不会有~~~
Jdk下的jVisualVM查看的，建议可以去检测一波，说不定确实有内存溢出的问题~~
只是建议哈。。。
